### ISSUE TITLE
Inconsistent language and typos

### ISSUE THREAD

**Issue by susannmt** [SPF-UiO/spbm#17]
The language need to be more consistent, both in regards to mixing English/Norwegian, abbreviations and language typos.

Example of undesired behaviour: 

![skjermbilde 2018-07-26 13 46 41](https://user-images.githubusercontent.com/8546399/43260740-a140b0c2-90da-11e8-8383-b691b11b00d2.png)
![skjermbilde 2018-07-26 14 02 41](https://user-images.githubusercontent.com/8546399/43261762-291b12dc-90de-11e8-801c-b7951dd52f18.png)

**Comment by thor** [comment]
Thank you so much for the issue -- you're absolutely right that there are plenty of inconsistencies, both as a result of inconsistent translating and a lack thereof.

If you follow https://github.com/SPF-UiO/spbm#getting-started-with-i18n, meaning the first step with extraction and merging, then you can edit locale/nb_NO/django.po. 

Could you take a look at it and create a pull request, @susannmt? :)
